### ISSUE TITLE
Interesting behavior on unification

### ISSUE THREAD

**Issue by KnowledgeGarden** [raydac/jprol#2]
Consider this script:
"topic. topicLocator(topic, TypeType). label(TypeType, 'Type Type Class')."
I am feeding it remotely with a consult call.
If I then run this goal: "label(X, Y)."
I see these results:
label(X,Y)
X{uid=3}=???
Y{uid=4}='Type Type Class'
where X should resolve to TypeType

If I run this goal: topicLocator(topic, Z).
I see these results:
topicLocator('topic',Z)
Z{uid=3}=???

Running similar code in SWI returns expected results.
I can see three candidate issues in play:
a) I am not writing my scripts properly (which would mean SWI is rather forgiving)
b) I am misusing the ReadMe's suggested code for direct access
c) Something in jprol unification is not running properly

Will be happy to learn what I might be doing wrong.
Many thanks
Jack

**Comment by raydac** [comment]
Hello, your script doesn't work well and under SWI-Prolog, the issue is that you forgot that Prolog recognizes all names started with a upper case char as variable names and both JProl and SWI-Prolog make unification of X with the TypeType as with a variable (!), in the case you have as the result - non initialized variable X and JProl shows ??? in the case and SWIProlog usually shows nothing
![swipl](https://cloud.githubusercontent.com/assets/3008810/9422967/76c80f8a-48b6-11e5-9335-1a70c158884b.png)

try `topic. topicLocator(topic, 'TypeType'). label('TypeType','Type Type Class').`

**Comment by KnowledgeGarden** [comment]
That changed everything. Thank you!
